import { BasePdfGenerator, PDFOptions } from '../base/BasePdfGenerator'
import { Document } from '../../../model/documents'
import { renderSection } from '../renderers/SectionRenderer'
import { renderField } from '../renderers/FieldRenderer'
import { renderNotes } from '../renderers/NotesRenderer'
import { PDF_CONFIG } from '../shared/pdfConfig'

function getDocumentTypeLabel(type: Document['type']): string {
  const labels = {
    'contract': 'Contract',
    'invoice': 'Invoice',
    'registration': 'Vehicle Registration',
    'insurance': 'Insurance Policy',
    'inspection': 'Technical Inspection Certificate',
    'tir-carnet': 'TIR Carnet',
    'adr': 'ADR Certificate',
    'hazmat-permit': 'Hazmat Transport Permit',
    'license': 'License',
    'certificate': 'Certificate',
    'other': 'Document'
  }
  return labels[type]
}

function getEntityTypeLabel(type: Document['entityType']): string {
  const labels = {
    'vehicle': 'Vehicle',
    'customer': 'Customer',
    'supplier': 'Supplier',
    'driver': 'Driver',
    'company': 'Company',
    'other': 'Other'
  }
  return labels[type]
}

function formatDate(date: string | Date): string {
  return new Intl.DateTimeFormat('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit'
  }).format(new Date(date))
}

/**
 * PDF Generator for Document entities
 */
export class DocumentPdfGenerator extends BasePdfGenerator {
  constructor(private document: Document, options: PDFOptions = {}) {
    super(options)
  }

  protected getTitle(): string {
    return getDocumentTypeLabel(this.document.type)
  }

  protected getFilename(): string {
    return `${this.document.name.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_${this.document.id}.pdf`
  }

  protected renderContent(): void {
    // Document Information Section
    renderSection(this.doc, 'Document Information', this.pageManager, this.styleManager)

    renderField(this.doc, 'Document Name:', this.document.name, this.pageManager, this.styleManager)
    renderField(this.doc, 'Document Type:', getDocumentTypeLabel(this.document.type), this.pageManager, this.styleManager)
    renderField(this.doc, 'Document ID:', this.document.id, this.pageManager, this.styleManager)

    if (this.document.number) {
      renderField(this.doc, 'Document Number:', this.document.number, this.pageManager, this.styleManager)
    }

    this.pageManager.addSpace(5)

    // Related Entity Section
    renderSection(this.doc, 'Related Entity', this.pageManager, this.styleManager)

    renderField(this.doc, 'Related To:', getEntityTypeLabel(this.document.entityType), this.pageManager, this.styleManager)
    renderField(this.doc, 'Entity Name:', this.document.entityName, this.pageManager, this.styleManager)
    renderField(this.doc, 'Entity ID:', this.document.entityId, this.pageManager, this.styleManager)

    this.pageManager.addSpace(5)

    // Important Dates Section
    renderSection(this.doc, 'Important Dates', this.pageManager, this.styleManager)

    renderField(this.doc, 'Issue Date:', formatDate(this.document.issueDate), this.pageManager, this.styleManager)

    if (this.document.expiryDate) {
      renderField(this.doc, 'Expiry Date:', formatDate(this.document.expiryDate), this.pageManager, this.styleManager)
    }

    renderField(this.doc, 'Created:', formatDate(this.document.createdAt), this.pageManager, this.styleManager)
    renderField(this.doc, 'Last Updated:', formatDate(this.document.updatedAt), this.pageManager, this.styleManager)

    this.pageManager.addSpace(5)

    // Issuing Authority Section (if exists)
    if (this.document.issuingAuthority) {
      renderSection(this.doc, 'Issuing Authority', this.pageManager, this.styleManager)
      renderField(this.doc, 'Authority:', this.document.issuingAuthority, this.pageManager, this.styleManager)
      this.pageManager.addSpace(5)
    }

    // Notes Section (if exists)
    if (this.document.notes) {
      renderSection(this.doc, 'Notes', this.pageManager, this.styleManager)
      renderNotes(this.doc, this.document.notes, this.pageManager, this.styleManager)
      this.pageManager.addSpace(5)
    }

    // Document Content Section
    renderSection(this.doc, 'Document Content', this.pageManager, this.styleManager)

    this.styleManager.setBodyFont()
    const yPos = this.pageManager.getCurrentY()
    this.doc.text('This is a sample document generated by the Deliveroo TMS system.', PDF_CONFIG.page.margin.left, yPos)
    this.pageManager.addSpace(6)
    this.doc.text('This document contains all the relevant information as stored in the system.', PDF_CONFIG.page.margin.left, this.pageManager.getCurrentY())
  }
}
